language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - composer self-update && composer --version
  - composer install --dev --prefer-source

script:
 - vendor/bin/phpunit -v -c $PWD/test/phpunit-travis.xml --coverage-clover=coverage.clover
 - ./.travis/tag_version.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
