name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug    
          tools: php-cs-fixer, phpunit
      
      - uses: php-actions/composer@dynamic-docker

      - name: PHPUnit Tests
        uses: php-actions/phpunit@dynamic-docker
        with:
          bootstrap: vendor/bin/phpunit # vendor/autoload.php
          configuration: test/phpunit-travis.xml
          args: --coverage-clover=coverage.clover
